### ISSUE TITLE
Change upper case for all letters

### ISSUE THREAD

**Issue by bredmich** [muCkk/skin.ace#4]
Hi MuCkk,
i´m jusing your skin for my kodi but want to change the upper case function.
Everything in the settings is set in uppercase and in german this looks pretty bad.

Is there a simple switch for this ?
So i could fork this skin to my personal repository.

Thanks
Michael

**Comment by muCkk** [comment]
Hi bredmich,

the fonts the skin uses are defined in /720p/Font.xml.  It will load all the fonts mentioned in this file from the /skin.ace/fonts directory. You can use the fonts in other XMLs using the names, (for example Font_20). If you want to change the font for the settings you should start by changing /720p/Settings.xml and perhaps other XMLs containing "settings" in the filename.

You could also change all the fonts in /720p/Font.xml and remove the uppercase statement.

Hope I could help.

**Comment by muCkk** [comment]
In case other people are interested in this:
Pull request: https://github.com/muCkk/skin.ace/pull/5
Commit: https://github.com/grantbeattie/skin.ace/commit/3a60cab2cdaa1a465e73ed70404c07f2c1f88635
